//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 24 22:15:57 EST 2019
//----------------------------------------------------
package CompiladorPascal;

/**
 * CUP generated class containing symbol constants.
 */
public class sym {

    /* terminals */
    public static final int crt = 5;
    public static final int texto = 19;
    public static final int tipo = 10;
    public static final int end = 26;
    public static final int writeln = 16;
    public static final int coma = 9;
    public static final int readkey = 25;
    public static final int ifF = 22;
    public static final int num = 8;
    public static final int program = 2;
    public static final int punto = 27;
    public static final int readln = 20;
    public static final int menorQ = 29;
    public static final int igual = 30;
    public static final int EOF = 0;
    public static final int clrscr = 14;
    public static final int menorOI = 32;
    public static final int id = 7;
    public static final int mayorQ = 28;
    public static final int error = 1;
    public static final int igualdad = 21;
    public static final int write = 15;
    public static final int fin = 3;
    public static final int inte = 11;
    public static final int then = 23;
    public static final int var = 6;
    public static final int mayorOI = 31;
    public static final int pi = 17;
    public static final int chare = 12;
    public static final int begin = 13;
    public static final int elseF = 24;
    public static final int uses = 4;
    public static final int pd = 18;
}
